# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
   
name: Web Client CI
on:
  push:

    branches: [ f/53_instructor_create_course ]
  pull_request:
    branches: [ f/53_instructor_create_course ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:

        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - working-directory: ./client
      run: npm ci
    - name: Create fake oauthconfig.json
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: "./client/src/oauthconfig.json"
        FILE_DATA: "{}"
    - working-directory: ./client
      run: npm run build --if-present
      env:
        CI: false
    - working-directory: ./client
      run: npm test -- Courses.test.js
